# Generated by Django 3.0.7 on 2020-06-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of education program', unique=True)),
                ('description', models.TextField(help_text='Description of education program')),
            ],
        ),
        migrations.CreateModel(
            name='ParamsWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField(help_text='Name of criteria')),
                ('value', models.FloatField(help_text='Value of coef')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(help_text='label of program criteria')),
                ('description', models.TextField(help_text='Description of education program')),
                ('value', models.FloatField(help_text='Value of education program')),
                ('timestamp', models.DateTimeField(help_text='Timestamp of education program')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display_charts.EduProgram')),
            ],
        ),
    ]
